### ISSUE TITLE
Bug: swagger extension is not working in production mode

### ISSUE THREAD

**Issue by PlesnikJakub** [3PillarGlobal-Czechia/interview-app-api#37]
When the application is deployed to the DEV environment swagger extension is not working due to the incorrect base path for endpoints.

Note: even its DEV environment asp.net env is "production" mode and this causes issue sin swaggerextension.cs to use incorrect path.

**Comment by PlesnikJakub** [comment]
@TerezaSkutova in src\WebApi\WebApi\Modules\SwaggerExtension.cs you can get fid off conditions inside for each loop. 
We don't have a reverse proxy so far, which means only the option currently in the first block of the condition should be used.

**Comment by PlesnikJakub** [comment]
Original behavior should be reproducible locally by changing ASPNETCORE_ENVIRONMENT.
In VS code in the context menu, under the run option, go to WebApiDebug properties, and there you can edit launch profiles and set "production".  

Let me know if that works 😊 

![image](https://user-images.githubusercontent.com/15345617/157716629-5e2ede4e-9012-4ccd-9125-72abea8b1308.png)

**Comment by TerezaSkutova** [comment]
@PlesnikJakub  It works perfectly. Thank you for that hint!
