### ISSUE TITLE
Improvement: File scoped namespaces as default

### ISSUE THREAD

**Issue by TomasNiemczyk98** [3PillarGlobal-Czechia/interview-app-api#82]
### Description
Since we are trying to enforce file scoped namespaces in the entire app we could try setting them as default. This can be done in .editorconfig file like this:

`
[*.cs]
csharp_style_namespace_declarations=file_scoped:warning
`

However there is currently a minor [bug](https://github.com/dotnet/roslyn/issues/60345) that's apparently fixed but not yet delivered in current visual studio 2022 version.

Do we make the change now or wait until it's fixed?

**Comment by petrspelos** [comment]
I'd still go for it, it's not like we won't notice, it straight up won't compile.

I sent @PlesnikJakub a draft of an `.editorconfig` that does include that rule.

**Comment by PlesnikJakub** [comment]
It seems we have thin included in the latest .editorconfig. Kudos to @petrspelos  and I am closing this issue.
