### ISSUE TITLE
API: Fix route names to follow REST best practice

### ISSUE THREAD

**Issue by PlesnikJakub** [3PillarGlobal-Czechia/interview-app-api#99]
## Description
The route for updating the order of questions inside the question set does not follow the REST naming standard.

In [QuestionSetController.cs](https://github.com/3PillarGlobal-Czechia/interview-app-api/blob/main/src/WebApi/WebApi/UseCases/v1/QuestionSet/UpdateQuestionOrder/QuestionSetController.cs)
**Current route**
`POST /api/v1/QuestionSet/{id}/UpdateQuestionOrder`

**Expected route**
`POST /api/v1/QuestionSet/{id}/OrderQuestions` 

Rename the route and regenerate the API CLient.

⚠️ If you find any other naming issues feel free to mention them in the comments and we can find out the way how to address them. 

## Acceptance Criteria
- [ ] Update the route URI
- [ ] Ensure E2E tests are passing
- [ ] Regenerate API Client

## Want to work on this issue? 

Amazing! 🌞 Let us know in the comment below and we will assign it to you.
Don't hesitate to ask for more info. We are here to help.

**Comment by obinnadtq** [comment]
Hi. I would like to work on this issue

**Comment by petrspelos** [comment]
@obinnadtq it's all yours, if you have any questions, feel free to ask. ☺️

**Comment by PlesnikJakub** [comment]
resolved 🚀
